[package]
name = "plots"
version = "0.1.0"
edition = "2018"

[dependencies]
cairo-rs = { version = "0.9.1", features = ["svg", "png", "ps"] }
libxml = "0.2.15"
either = "1.6.1"
regex = { version = "1.4.2" }
serde = { version="1.0.130", features=["derive"] }
serde_json = "1.0.68"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
showable = { path = "../showable" }


